(add-to-list 'winner-boring-buffers "*helm M-x*")
(add-to-list 'winner-boring-buffers "*helm mini*")
(add-to-list 'winner-boring-buffers "*Helm Completions*")
(add-to-list 'winner-boring-buffers "*Helm Find Files*")
(add-to-list 'winner-boring-buffers "*helm mu*")
(add-to-list 'winner-boring-buffers "*helm mu contacts*")
(add-to-list 'winner-boring-buffers "*helm-mode-describe-variable*")
(add-to-list 'winner-boring-buffers "*helm-mode-describe-function*")

(provide 'init-winner)
